feat: first hw
truefalsemary/Flutter-todo-app pull request #1
Opened 2024-06-23 04:53 UTC by truefalsemary

2024-06-24 10:38 UTC, vilorg requested changes
Приветик!
Посмотрел бегло. Давай исправь - после этого посмотрим подробнее)

2024-06-24 10:38 UTC, vilorg commented on lib/main.dart
> +    print('${record.loggerName}: ${record.level.name}:  ${record.message}');
Приветик. Это че такое?)))
 Logger.e(и сюда принтишь что нужно)
 Почитай доку - https://pub.dev/packages/logger

2024-06-24 10:38 UTC, vilorg commented on lib/ui/main_screen.dart
> +class MySliverPersistentHeaderDelegate extends SliverPersistentHeaderDelegate {
хмм, у меня при запуске эксепшин при запуске:

════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
SliverGeometry is not valid: The "layoutExtent" exceeds the "paintExtent".
The paintExtent is 88.0, but the layoutExtent is 146.8.
The RenderSliver that returned the offending geometry was: _RenderSliverPinnedPersistentHeaderForWidgets#095a8 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.reverse, scrollOffset: 1.2, precedingScrollExtent: 0.0, remainingPaintExtent: 932.0, crossAxisExtent: 430.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 932.0, remainingCacheExtent: 1183.2, cacheOrigin: -1.2)
    geometry: SliverGeometry(scrollExtent: 148.0, paintExtent: 88.0, layoutExtent: 146.8, maxPaintExtent: 148.0, hasVisualOverflow: true, cacheExtent: 148.0)
        scrollExtent: 148.0
        paintExtent: 88.0
        layoutExtent: 146.8
        maxPaintExtent: 148.0
        hasVisualOverflow: true
        cacheExtent: 148.0
    maxExtent: 148.0
    child position: 0.0
    child: RenderConstrainedBox#c88bb relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: <none> (can use size)
        constraints: BoxConstraints(w=430.0, 0.0<=h<=146.8)
        size: Size(430.0, 88.0)
        additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=88.0)
        child: RenderDecoratedBox#8ab3f NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: <none> (can use size)
            constraints: BoxConstraints(w=430.0, h=88.0)
            size: Size(430.0, 88.0)
            decoration: BoxDecoration
                color: Color(0xfff7f6f2)
                boxShadow: BoxShadow(Color(0xff000000), Offset(0.0, 0.0), 10.0, 0.0, BlurStyle.normal)
            configuration: ImageConfiguration(bundle: PlatformAssetBundle#408ba(), devicePixelRatio: 3.0, locale: en_US, textDirection: TextDirection.ltr, platform: iOS)
            child: RenderPadding#1f05a NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                parentData: <none> (can use size)
                constraints: BoxConstraints(w=430.0, h=88.0)
                size: Size(430.0, 88.0)
                padding: EdgeInsets(16.0, 0.0, 18.0, 16.0)
                textDirection: ltr
                child: RenderFlex#2e749 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                    parentData: offset=Offset(16.0, 0.0) (can use size)
                    constraints: BoxConstraints(w=396.0, h=72.0)
                    size: Size(396.0, 72.0)
                    direction: horizontal
                    mainAxisAlignment: spaceBetween
                    mainAxisSize: max
                    crossAxisAlignment: end
                    textDirection: ltr
                    verticalDirection: down

The relevant error-causing widget was:
    SliverPersistentHeader SliverPersistentHeader:file:///Users/developer/Downloads/Flutter-todo-app/lib/ui/main_screen.dart:24:15

When the exception was thrown, this was the stack:

2024-06-24 10:38 UTC, vilorg commented on lib/ui/main_screen.dart
> +class MySliverPersistentHeaderDelegate extends SliverPersistentHeaderDelegate {
![image](https://github.com/truefalsemary/Flutter-todo-app/assets/60550560/6f1867e2-d626-4a9d-a59a-e3ae35215da3)
Хотелось бы плавную анимашку, а то просто хедер уходит вверх, и освобождает пространство
Посмотри SliverPersistentHeader

2024-06-24 10:38 UTC, vilorg commented on lib/ui/main_screen.dart
> +class MySliverPersistentHeaderDelegate extends SliverPersistentHeaderDelegate {
Также добавил бы в хедер SafeArea, чтоб артефактов не было

2024-06-24 10:38 UTC, vilorg commented on lib/ui/main_screen.dart
> +    return Builder(builder: (context) {
Билдер использовать - очень плохо отражается на ресурсах. По-хорошему - избавляемся от него.

2024-06-24 10:38 UTC, vilorg commented on lib/ui/todo_screen.dart
> +                  const Divider(color: Colors.grey),
![image](https://github.com/truefalsemary/Flutter-todo-app/assets/60550560/0ebd1641-e4d1-4b95-90f8-be8baaab1a1f)
Здесь придерусь с точки зрения эстетики. Выглядит подчеркивание под подчеркиванием. Немного крипово. Можно форму DropDown использовать.
https://stackoverflow.com/questions/53150219/how-to-make-rounded-border-for-dropdownbutton-in-flutter

2024-06-24 10:38 UTC, vilorg commented on lib/ui/todo_screen.dart
> +                  const _DescriptionTextField(),
![image](https://github.com/truefalsemary/Flutter-todo-app/assets/60550560/65e0f494-31ee-4973-ae65-fcbdbb17e830)
Тут у нас курсор белого цвета, что не оч ок. Смысл от него тогда какой?
https://stackoverflow.com/questions/55991901/how-to-change-cursor-color-in-flutter

2024-06-24 10:38 UTC, vilorg commented on lib/data/todo_entity.dart
> +  final int id;
Тут тебе будет сложно отслеживать уникальность id. Вместо этого используй конструкцию UUID, которая будет автоматом генерировать уникальный id:
https://pub.dev/packages/uuid

2024-06-24 10:38 UTC, vilorg commented on lib/data/todo_entity.dart
> +      case Priority.high:
![image](https://github.com/truefalsemary/Flutter-todo-app/assets/60550560/afd84ea7-f15b-42da-956f-fb362ef9c00c)
Посмотрел нейминг коммитов, это что?)

2024-06-24 10:38 UTC, vilorg commented on lib/domain/many_todos_bloc/many_todo_event.dart
> +sealed class ManyTodosEvent extends Equatable {
Смотри. 
Во первых - что за нейминг ManyTodo?))
Во вторых - чтобы много состояний не делать, и в них не путаться - посмотри в сторону cubit:
https://habr.com/ru/companies/simbirsoft/articles/573848/

2024-06-24 10:38 UTC, vilorg commented on pubspec.lock
>      version: "0.0.0"
Зачем использовать flutter_test, если ты его не используешь?)

2024-06-24 10:38 UTC, vilorg commented on lib/ui/main_screen.dart
Очень много букав. Сложно читать. Надо уметь разделять классы на файлы, чтобы лучше читалось:
https://www.reddit.com/r/FlutterDev/comments/1bl9oyo/splitting_up_a_large_file_best_practices/

2024-06-24 10:38 UTC, vilorg commented on lib/ui/todo_screen.dart
> +        final manyState = context.read<ManyTodosBloc>().state;
Смотри, поизучай виджеты bloc
https://pub.dev/packages/flutter_bloc

 Можно использовать какой нибудь BlocListener или BlocProvider. Там можно все посмотреть и не использовать Builder

2024-06-24 10:38 UTC, vilorg commented on lib/ui/main_screen.dart
Также смотри. Ты же можешь создать папочки pages, widgets. Чтобы разделить по уровням виджеты. А то у тебя накинуто все в кучу. Очень сложно поймать смысл какой то (

2024-06-24 11:40 UTC, truefalsemary commented on lib/ui/todo_screen.dart
> +        final manyState = context.read<ManyTodosBloc>().state;
не вижу смысла следить за состоянием блока, так как обращаюсь к нему только за тем, чтобы вызвать ивенты

2024-06-24 11:41 UTC, truefalsemary commented on lib/ui/main_screen.dart
приватные виджеты вынесу в классы и сделаю через part of, просто тупа не успела(

2024-06-24 11:42 UTC, truefalsemary commented on lib/domain/many_todos_bloc/many_todo_event.dart
> +sealed class ManyTodosEvent extends Equatable {
это ивенты для блока, которые отвечает за все заметки, поэтому many

2024-06-24 11:44 UTC, truefalsemary commented on lib/ui/main_screen.dart
> +class MySliverPersistentHeaderDelegate extends SliverPersistentHeaderDelegate {
я реализовала через делегат свою имплементацию, анимашку добавлю

2024-06-24 11:47 UTC, truefalsemary commented on lib/main.dart
> +    print('${record.loggerName}: ${record.level.name}:  ${record.message}');
просто переписываю принт у логеров, чтобы выводить название логгера, уровень и сообщением соответственно, кста я использую пакет logging, а не logger: https://pub.dev/packages/logging и в доке как раз и описано использование

2024-06-24 11:47 UTC, truefalsemary commented on pubspec.lock
>      version: "0.0.0"
потому что тесты в планах написать))

2024-06-24 11:48 UTC, truefalsemary commented on lib/ui/todo_screen.dart
> +                  const Divider(color: Colors.grey),
нифига как фигово на айфонах выглядит, на андроиде не так

2024-06-24 11:50 UTC, truefalsemary commented on lib/ui/main_screen.dart
> +    return Builder(builder: (context) {
это хорошее замечание, забыла убрать

2024-06-24 12:00 UTC, truefalsemary commented on lib/ui/todo_screen.dart
> +        final manyState = context.read<ManyTodosBloc>().state;
не особо вижу смысл использовать не билдер, так как весь стейт это это тудушки

2024-06-24 21:20 UTC, Glitchy-Sheep commented on android/app/src/main/AndroidManifest.xml
>          android:label="flutter_todo_app"
Небольшая подсказка: если в манифесте поменять label на Flutter Todo App, 
то это будет менять название программы и в списке приложений системы,
что смотрится довольно симпатично, рекомендую попробовать:)

2024-06-24 21:21 UTC, Glitchy-Sheep commented on lib/data/todo_entity.dart
> +      case Priority.high:
Это отчаяние, и, предположительно, усталость 😁

2024-06-24 21:24 UTC, Glitchy-Sheep commented on lib/data/todo_entity.dart
> +}
Смотри как можно классно сделать метод частью enum:

```dart
enum Priority {
  no,
  low,
  high;

  String parseToString() {
    switch (this) {
      case Priority.no:
        return 'no';
      case Priority.low:
        return 'low';
      case Priority.high:
        return 'high';
    }
  }
}
```

Этот механизм называется enhanced enum, чтобы его задействовать
перечисляй значения через запятую, но после последнего поставь `;`

Таким образом ты сможешь встраивать в enum свои собственные методы
и даже конструкторы более сложных значений:

https://dart.dev/language/enums#declaring-enhanced-enums

2024-06-24 21:30 UTC, Glitchy-Sheep commented on lib/data/todo_repo.dart
> +
(*⭐) Классно, что есть задел на архитектуру и сделан моковый репозиторий задач.







p/s: "Счастье можно найти даже в самые темные времена, если не забывать обращаться к свету." ^^

2024-06-24 21:35 UTC, Glitchy-Sheep commented on lib/domain/many_todos_bloc/many_todo_event.dart
> +sealed class ManyTodosEvent extends Equatable {
По поводу нейминга, пожалуй тоже соглашусь, можно попробовать следующие варианты:

1. AddTodo
2. RemoveTodo
3. MarkTodoAsDone
4. MarkTodoAsNotDone
5. Get/LoadTodo
...

Эти ивенты будет вызывать UI, поэтому думаю должно быть повелительное наклонение/императив.

Таким образом при нажатии на добавить (при заполненных полях) отправляется ивент Add,
то есть мы как бы просим "Добавь задачу".
при удалении отправляется ивент remove (с id задачи скажем), и так далее.

2024-06-24 21:45 UTC, Glitchy-Sheep commented on lib/domain/many_todos_bloc/many_todo_state.dart
> +}
Возможно есть смысл назвать стейт (по аналогии с ивентами) LoadingTodos.

Т.е. название должно недвусмысленно и чётко отражать состояние.

InProgress слегка обобщённо звучит, не сразу понятно "что именно" в процессе.

Аналогично с ManyTodosSuccess -> TodoLoadingSuccess.

2024-06-24 21:55 UTC, Glitchy-Sheep commented on lib/domain/many_todos_bloc/many_todos_bloc.dart
> +  }
Небольшое замечание:
Я думаю тут уместнее будет сперва удалить задачу, а потом эмитить состояние.

Что-то такое:
```dart
_repo.deleteTodo(even.todo.id)
final todos = (state as ManyTodosSuccess)
    .todos
    .deleteWhere((todo) => todo.id == even.todo.id);

emit(ManyTodosSuccess(todos));
```

В таком случае при появлении бека мы сперва попробуем удалить задачу, и только в случае
отсутствия ошибки — выпустим новое состояние.

2024-06-24 21:57 UTC, Glitchy-Sheep commented on lib/domain/many_todos_bloc/many_todos_bloc.dart
> +  FutureOr<void> _onSaveManyTodos(
Опять же, пример небольшой путанницы в нейминге.

Как человек, который видит код впервые, мне кажется, что этот метод сохраняет несколько задач (ManyTodos).

Было бы круто описать его скорее как _onSaveTodo или _onEditTodo.

2024-06-24 22:03 UTC, Glitchy-Sheep commented on lib/main.dart
> +            shape: CircleBorder(),
Очень советую вынести стилистические объекты в какую-нибудь отдельную директорию/модуль.

Явное определение стилей в main файле сильно нагружает точку входа. Плюс, по файлу слегка тяжелее ориентироваться.

Это можно сделать так:
1. app_fonts
2. app_color_palletes
3. app_themes

В каждом из модулей будут классы со статическими константами, тогда ты точно не потеряешься в дальнейшем,
особенно в случае изменения чего-то в дизайне (например одного цвета на другой), решение будет проще поддерживать.

У меня в репозитории есть пример попытки такого разделения.
(Папка uikit)

2024-06-24 22:04 UTC, Glitchy-Sheep commented on lib/main.dart
> +          useMaterial3: true,
По дизайну в фигме можно понять, что скорее всего используется именно material2 (свич и floating action button себя выдают), поэтому тут лучше выбрать false.

2024-06-24 22:08 UTC, Glitchy-Sheep commented on lib/main.dart
> +          ManyTodosBloc(MockTodosRepo())..add(const ManyTodosLoaded()),
Вот тут могут появиться сложности в понимании именования.

Для меня это выглядит как запрос "Много задач загружены"
Слегка сменив формулировку можно облегчить семантику: "Загрузить все задачи" -> LoadAllTodos

Также можно добавить запятую после
```dart
const ManyTodosLoaded() <---- 
```

Тогда автоформаттер разобьёт код красивым образом.

2024-06-24 22:09 UTC, Glitchy-Sheep commented on lib/main.dart
> +        },
(*⭐): Прикольный задел на декларативный роутинг.

2024-06-24 22:12 UTC, Glitchy-Sheep commented on lib/main.dart
> +  Logger.root.level = Level.ALL;
В библиотеке foundation фреймворка есть крутая константа kDebugMode и kReleaseMode

И та и другая соответственно равна true если включен debug и true если релиз.

Ты можешь использовать это, чтобы заставить логгер выключаться в релизе:

```dart
Logger.root.level = kDebugMode ? Level.ALL : Level.OFF;
// Насчёт OFF только не уверен, у меня другой логгер :)
```

2024-06-24 22:15 UTC, Glitchy-Sheep commented on lib/main.dart
>    runApp(const MyApp());
Очень (очень-очень на самом деле) советую добавить сюда runZonedGuarded 
с обработчиком ошибок, в котором будут логироваться эти самые ошибки.

Так, при малейшем чихе фреймворка, ты будешь видеть в консоли ошибку, её описание
и даже стектрейс (если конечно ты его выведешь).

Этот механизм упоминался в одной из лекций как must have.

Пример можно также посмотреть у меня в репозитории в main.dart

2024-06-24 22:22 UTC, Glitchy-Sheep commented
Заметил не очень хорошую деталь, файл app-release.apk был закоммичен в readmi_images как часть проекта.
Его лучше загрузить во вкладке releases на гитхабе (справа от списка файлов на главной странице репозитория):

![image](https://github.com/truefalsemary/Flutter-todo-app/assets/93445878/86cf28f5-8f01-4f17-a704-3212de040f23)

Этот раздел на гитхабе как раз сделан для публикации готовых бинарных файлов.
В случае коммита такого файла в репозиторий увеличивается размер проекта при клонировании репозитория (иногда значительно).

Также лучше readmi_images переименовать в readme_images, либо ещё проще -> screenshots

2024-06-24 22:47 UTC, Glitchy-Sheep commented on lib/ui/todo_screen.dart
> +      child: Visibility(
На самом деле здесь не должно быть Visibility, нужно просто активировать TextButton
и деактивировать её через onPressed (если передан null - деактивирована, и наоборот).

![image](https://github.com/truefalsemary/Flutter-todo-app/assets/93445878/79a6d6b6-6a06-4b8e-8d89-628a3577d224)

2024-06-24 22:49 UTC, Glitchy-Sheep commented on lib/ui/todo_screen.dart
> +            },
На мой взгляд, очень хорошая практика выносить onPressed в отдельные 
методы. Так мы можем сильно повысить читабельность кода.

Именно про эту фишку я чаще всего сам забываю, но она очень простая и эффективная. :)

```dart
// В случае если нужны параметры
onPressed: () => _yourMethod(args),

// И если не нужны
onPressed: _yourMethod,
```

2024-06-24 22:51 UTC, Glitchy-Sheep commented on lib/ui/todo_screen.dart
> +  }
Возможно имеет смысл вынести этот метод в отдельный файл или модуль (date_formatters.dart например).

А сам файл держать, скажем, в папке lib/utils

2024-06-24 22:57 UTC, Glitchy-Sheep commented on lib/ui/todo_screen.dart
> +                  lastDate: DateTime(2101),
К 2101 году приложение устареет :DD

Шутка, но с долей правды.
Тут можно использовать трюк с прибавлением дат:
```dart
DateTime.now().add(const Duration(days: 365 * 100)),
```

Кажется есть более элегентный способ это сделать, но я не уверен, что вспомню.
(Самое смешно, что я тоже дату захардкодил, и даже не подумал про это :PP)

2024-06-24 23:03 UTC, Glitchy-Sheep commented on lib/ui/todo_screen.dart
> +                ]),
К сожалению тут не хватит обычного AppBar,
такое поведение с закрывающимся AppBar-ом достигается с помощью Sliver-ов.

Сперва это может быть слегка тяжеловато.
Можешь посмотреть пример реализации в моём репозитории, но я пока не сделал анимацию для него.

Также явно не стоит оборачивать весь Scaffold в билдер, это слегка странно смотрится, тут очень советую прочитать документацию по блоку (от начала до конца, без примеров).

Я понимаю почему именно был включен Builder, чтобы можно было получить InheritedWidget, предоставленный провайдером, но это можно было бы сделать в другом виде, как мне кажется.

Либо с помощью декомпозиции вынести Scaffold в компонент, и провайдить notifier уже в этот компонент. Тогда нужда в билдере отпадёт сама по себе.

2024-06-24 23:07 UTC, Glitchy-Sheep commented on lib/ui/todo_screen.dart
> +          boxShadow: [
На самом деле тут 2 тени

![image](https://github.com/truefalsemary/Flutter-todo-app/assets/93445878/aaad2e12-6031-4d1b-b745-1835ae4f3bae)

В фигме можно узнать подробную информацию про тень, тыкнув на компонент, и справа в списке свойств в самом низу есть солнышко у теней, оно открывает подробности.

2024-06-24 23:12 UTC, Glitchy-Sheep commented on lib/domain/todo_notifier/one_todo_notifier.dart
> +    required int id,
Поле id явно дублирующее, т.к. оно фактически содержится в задаче todo.

Также есть сомнения по поводу необходимости использования ChangeNotifier.
Я понимаю желание сделать интерактивные туду, но на текущем этапе это могло тебя очень запутать.

Лучше выбрать итеративный подход, с постепенным наслоением, чтобы не держать в голове все задачи сразу 💖

2024-06-24 23:15 UTC, Glitchy-Sheep commented on lib/ui/app_checkbox.dart
> +              : const Color(0xFF34C759);
На самом деле, сейчас может быть довольно тяжело работать с цветами и темами,
т.к. они указаны в main файле и не очень структурированы.

Поэтому можешь полностью забрать соответствующие файлы с моего репозитория в директории uikit и применить в своём решении. Если это облегчит тебе работу, то я буду очень рад.

2024-06-24 23:18 UTC, Glitchy-Sheep commented on lib/ui/app_material_wrapper.dart
> +}
Мне кажется отдельный класс для простого SizedBox явно лишний.
Также сходу возникает вопрос "для чего он" и "где используется",
а сам этот файл ответ  на эти два вопроса дать к сожалению не может.

Через инструменты поиска обращений к этому классу я понял, что это обёртка над иконками,
чтобы у них был размер 24x24, но опять же, лучше использовать SizedBox inplace.

2024-06-24 23:19 UTC, Glitchy-Sheep commented on lib/ui/todo_screen.dart
> +                ]),
UPD: упс, не туда посмотрел, тут AppBar окей, я думал, что нахожусь в файле отображения задач ^^

2024-06-24 23:22 UTC, Glitchy-Sheep commented on lib/ui/main_screen.dart
> +class MySliverPersistentHeaderDelegate extends SliverPersistentHeaderDelegate {
Присоединяюсь к вопросу об exception-е, он явно есть, связан с параметрами paintExtent/layoutExtent а также с их значениями (размеры 88, 146.8 и т.п.) 

Исключение падает стабильно, поэтому нужно будет его отловить и исправить.

2024-06-24 23:24 UTC, Glitchy-Sheep commented on lib/ui/main_screen.dart
> +class MySliverPersistentHeaderDelegate extends SliverPersistentHeaderDelegate {
Советую посмотреть решения других ребят и попробовать плавно переписать их под себя, так будет проще: не придётся тратить уйму сил для поиска ошибки и сразу будет ясен нужный подход.

2024-06-24 23:26 UTC, Glitchy-Sheep commented on lib/ui/main_screen.dart
> +      ),
ColoredBox можно вынести в отдельный виджет и переиспользовать как в background так и в secondaryBackground.

Пример такой декомпозиции можно найти у меня в репозитории.

2024-06-24 23:29 UTC, Glitchy-Sheep approved these changes
Поздравляю с первым пережитым дедлайном, есть моменты, которые точно стоит исправить, но ты молодец, так держать :)

2024-06-25 05:53 UTC, truefalsemary commented on lib/main.dart
> +          useMaterial3: true,
В комментах отвечали, что возможны отклонения от дизайна, поэтому можно использовать material 3

2024-06-25 05:55 UTC, truefalsemary commented on lib/ui/todo_screen.dart
> +      child: Visibility(
Решила добавить, чтобы не была возможность удаления новой заметки, так как она ещё не добавлена, а значит и удалить мы её не можем, кажется логичным

2024-06-25 05:56 UTC, truefalsemary commented on lib/ui/main_screen.dart
> +      ),
Такое тёплое и конструктивное ревью, спасибо огромное!)

2024-06-25 06:14 UTC, truefalsemary commented on lib/ui/main_screen.dart
> +class MySliverPersistentHeaderDelegate extends SliverPersistentHeaderDelegate {
потратила уйму времени на ошибку и таки нашла, запушила))

2024-06-26 05:36 UTC, Glitchy-Sheep commented on lib/ui/common/app_fonts.dart
> +  static TextStyle b1 = const TextStyle(
Лучше использовать static const = value, нежели static = const value.

Константа в начале распространяется на всё выражение.
Более того, насколько я правильно понимаю, в первом случае это будет константа времени компиляции, а во втором константа времени выполнения.

Т.о. лучше использовать первый вариант определения для создания неизменяемых структур, известных на этапе компиляции.

2024-06-26 06:48 UTC, truefalsemary commented on lib/ui/common/app_fonts.dart
> +  static TextStyle b1 = const TextStyle(
Не знала, спасибо!)

2024-06-29 08:28 UTC, merged

2024-06-30 12:40 UTC, vilorg commented on lib/main.dart
> +    print('${record.loggerName}: ${record.level.name}:  ${record.message}');
Смотри, под капотом он не использует принт, а использует скорее debugPrint